### PR TITLE
Upgrade all dependencies and cargo fmt

### PR DESCRIPTION
**Pull request by Mange**
First commit upgrades all dependencies and makes the code compile again. This makes it possible to compile the crate even if OpenSSL 1.1.1 is installed on the machine.
(`reqwest` depends on `openssl` crate, see [`openssl` crate's changelog for 0.10.14](https://github.com/sfackler/rust-openssl/blob/master/CHANGELOG.md#v0104---2018-02-18))

Second commit is the result of `cargo fmt` to make it easier to work on the project from now on.
This is kept separately to make it easier to ignore this commit if you dislike it.

I have not been able to run the tests as I don't have credentials for a test account. I hope you are able to run them yourself before merging.

Let me know if I should do anything more. Thank you!

### CODE REVIEW

**Comment by nocduro** [comment]
Thanks for the PR!

Sorry for the late reply, was taking a break over the holidays and right now I'm studying for a couple interviews so my time has been more limited than usual.

I should get around to merging this by the end of next week (from a quick glance it lgtm), just want to test on my machine before merging. If I forget, just reply here and I'll come back to it.

As a side note, I'm not totally happy with the architecture of this crate (hence why it's not published on crates.io) so the API might change a ton if I ever get around to working on it again.

Thanks again!

**Comment by Mange** [comment]
I have actually extended the API a bit in my fork, so expect more PRs if this gets accepted. 😊

Enjoy your break, and good luck with your interviews. There should be no rush with this PR.

**Comment by nocduro** [comment]
Tests passed! In the time it took me to merge this, some more patches were released... So I added another commit to update them again 68683ca

**Comment by Mange** [comment]
That's great!

**Pull request merged**
